pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from version control
                git 'https://github.com/Drashti1603/Automation.git'
            }
        }
        
        stage('Run Robot Tests') {
            steps {
                // Execute Robot Framework tests
                sh 'robot --outputdir output /home/drashti/Documents/Android_Automation/robot-files/Web_Automation/Robot_Files/Amazon_Automation/Test_cases/Search_login_cart.robot'
            }
        }
        
        stage('Publish Test Results') {
            steps {
                // Publish test results using JUnit plugin
                junit 'output/output.xml' // Specify the path to the output.xml file generated by Robot Framework
            }
        }
    }
}
